name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6
    - run: npm ci
    - run: npm run test:verify
    - uses: codecov/codecov-action@v3
      with:
        directory: ./coverage